kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operator-v0.5
subjects:
- kind: ServiceAccount
  name: operator-v0.5
roleRef:
  kind: Role
  name: operator-v0.5
  apiGroup: rbac.authorization.k8s.io
